# Setup
title:               Coffee chat
tagline:             with a stranger
description:         'Curation of studies, techs, ideas and her journey as a maching learning engineer'
url:                 'https://alatteaday.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jiyun
  url:               
  email:             jyuun.k@gmail.com

# Gems
plugins:
  - jekyll-paginate 
  - jekyll-polyglot

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Polyglot
languages: ["en", "ko"] # 지원하고자 하는 언어
default_lang: "ko" # 컨텐츠의 기본 언어
exclude_from_localization: ["image"] # 루트 레벨 폴더 중 다국어 기능 제외 시킬 폴더
parallel_localizaion: true # 윈도우에서는 버그가 있어서 false로 해야 동작한다고 합니다.

sass:
  sourcemap: never